server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: shoppera
          uri: lb://shoppera
          predicates:
            - Path=/brand/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/