spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: eureka-client
          uri: lb://eureka-client
          predicates:
            - Path=/client/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/